import type { Metadata } from "next";
import { Inter, Monoton } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });
const monoton = Monoton({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: "Next.js, TypeScript",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* フォントを変更する場合 */}
      {/* <body className={monoton.className}> */}
      <body className={inter.className}>
        <Navbar />
        <main className="max-w-3xl mx-auto py-4">{children}</main>
      </body>
    </html>
  );
}
